resources:
- backend/deploy.yml
- backend/service.yml
- ingress.yml

images:
- name: 273444517440.dkr.ecr.us-east-1.amazonaws.com/labs-dvn-repo/dev/backend
  newName: 273444517440.dkr.ecr.us-east-1.amazonaws.com/labs-dvn-repo/dev/backend
  newTag: v1.0
- name: backend
  newName: 273444517440.dkr.ecr.us-east-1.amazonaws.com/labs-dvn-repo/dev/backend=273444517440.dkr.ecr.us-east-1.amazonaws.com
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
