resources:
- backend/deploy.yml
- backend/service.yml
- ingress.yml

images:
- name: 273444517440.dkr.ecr.us-east-1.amazonaws.com/labs-dvn-repo/dev/backend
  newName: 273444517440.dkr.ecr.us-east-1.amazonaws.com/labs-dvn-repo/dev/backend
  newTag: a60c80030b9ce48b03ac485470579cfc9d4ed422
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
